# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://automox.com/docs
port: 4002

title: Automox Documentation | Automox
author: Automox
description: Automox Documentation

twitter_username: automoxapp
github_username:  patchsimple
email: support@automox.com

date_format: "ordinal"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/

source: source
destination: public
css_destination: stylesheets
js_destination: javascripts
plugins_dir: plugins

markdown: kramdown
theme: minima

titlecase: true       # Converts page and post titles to titlecase

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
